### ISSUE TITLE
회원가입 API 만들기

### ISSUE THREAD

**Issue by hryuulkim** [Ryulth/timeline-backend#1]
## 회원가입 API 만들기
* /apis/accounts/register
* /apis/accounts/duplicate/{email}

### Required Field
* 이메일 아이디
* 사용자 이름
* 비밀번호
* 지역
* 학교
* 생년월일

### TODO
- [x] 아이디 중복검사 API 
- [x] 이메일은 UK 로 테이블 만들기
- [x] 회원가입시 JWT 토큰 생성 후 반환
